### ISSUE TITLE
Cant use call button 

### ISSUE THREAD

**Issue by Yuzuru07** [Snehasis4321/contacts_app_flutter_firebase#1]
I/UrlLauncher(28317): component name for tel:+62895634702777 is null
E/flutter (28317): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Tidak bisa menjalankan tel:+62895634702777 
E/flutter (28317): #0      _HomePageState.callUser (package:kontak/views/home.dart:39:7)
E/flutter (28317): <asynchronous suspension>

Does it need to send "name" too?

**Comment by Snehasis4321** [comment]
## if your android emulator is greater than API 30 then you will receive this error.

Add this in 

> "contacts_app\android\app\src\main\AndroidManifest.xml"

```xml
<queries>
  <!-- If your app checks for SMS support -->
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="sms" />
  </intent>
  <!-- If your app checks for call support -->
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="tel" />
  </intent>
  <!-- If your application checks for inAppBrowserView launch mode support -->
  <intent>
    <action android:name="android.support.customtabs.action.CustomTabsService" />
  </intent>
</queries>
```

This code will be below ```</application>``` and above ```</manifest>```

## Like This

![image](https://github.com/Snehasis4321/contacts_app_flutter_firebase/assets/96995340/e0086c4a-6449-47e2-af05-e19bf2f64ebf)
